# ple_simplehgn
model: MMOE
## data setting
# dataset
dataset: DBLP
# task 
Target_Node_Type: ['author', 'paper'] 
task_name: ['author', 'paper']  
task_to_node: {'author':'author', 'paper':'paper'}
task_type: {'author':'single-label', 'paper':'single-label'} 
task_graph_type: ['nc', 'nc']  
class_num: [4, 20]


## training setting 
rerun_num: 10
# epoch
train_epoch: 2000
iter_num: 1
early_stop: 40
# optimizer
learning_rate: 0.0005
weight_decay: 0 
# metric
save_metric: loss  # micro
# recorder
recorder_type: ['gate', 'att']

# different weight for different tasks
loss_weight_decay: True


## evaluation setting
eval_inter_ep: 10

## SimpleHGN paramter
# model
layer_num: 3
node_feature_hid_len: 64  # len of embedding feature
GAT_hid_len: 64 
edge_feats_len: 64
edge_residual_alpha: 0  # default: 0.05
dropout: 0


## PLE paramter
# expert_num:
shared_expert_num: 3
specific_expert_num: 3
# try method
# gate_type
gate_type: mlp 
## PLE model structure
num_levels: 3

mmoe: True

