# simplehgn
model: SimpleHGN
## data setting
# dataset
dataset: DBLP
# task 
Target_Node_Type: ['author', 'paper'] 
task_name: ['author', 'paper']  
task_to_node: {'author':'author', 'paper':'paper'}
task_type: {'author':'single-label', 'paper':'single-label'} 
task_graph_type: ['nc', 'nc']  
class_num: [4, 20]

# Target_Node_Type: ['author']
# task_name: ['author'] 
# task_to_node: {'author':'author'} 
# task_type: {'author':'single-label'} 
# task_graph_type: ['nc'] 
# class_num: [4]

# Target_Node_Type: ['paper'] 
# task_name: ['paper'] 
# task_to_node: {'paper':'paper'}
# task_type: {'paper':'single-label'} 
# task_graph_type: ['nc'] 
# class_num: [20]




## training setting 
rerun_num: 5
# epoch
train_epoch: 2000
iter_num: 1
early_stop: 40
# optimizer
learning_rate: 0.001
weight_decay: 0 
# metric
save_metric: loss
# recorder
recorder_type: ['att']

## evaluation setting
eval_inter_ep: 10


## SimpleHGN paramter
layer_num: 3
node_feature_hid_len: 64 # len of embedding feature
GAT_hid_len: 64
edge_feats_len: 64
edge_residual_alpha: 0.
dropout: 0.5

multi_tower: True

